### PR TITLE
Heroku deploy

### PR DESCRIPTION
**Pull request by skmp**
So, I started playing with the idea to deploy to heroku (free & managed)

Their guide is [here](https://devcenter.heroku.com/articles/getting-started-with-django#declare-process-types-with-procfile)

So far I've added a deploy script and requirements.txt (via pip freeze from my server). I've also invited both of you on the heroku project.

### CODE REVIEW

**Comment by frogg** [comment]
🤔

**Comment by skmp** [comment]
Was going over my old-and-stale PRs and though this is unlikely to get merged. I don't even know if this code works anymore :)

**Comment by frogg** [comment]
Haha Nice ;) what are you up to nowadays?

**Comment by skmp** [comment]
Open source wise, trying to maintain/coordinate an old project I have (reicast), and also some art project the past few years. Work wise, been doing low level work for nvidia lately. Mnn otherwise, traveling a lot! How about you?

**Comment by frogg** [comment]
Sounds nice. I've been working on some open source projects as well, like Processing for iOS, published some new cool apps (iRedpoint Boulder Fitness Tracker for Apple Watch, QuickScreen), finished my Bachelor's, did an Internship at Apple and moved to Berlin recently 😃

**Pull request closed without merging**
